// src/pages/index.tsx
import React, {FC} from 'react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import styles from '../../styles/Home.module.scss'
import Background from './background'

const Home: FC = ({text}:any) => {
  return (
    <>
      <div className={styles.center}>
        <h1 className={styles.title}>
          {text}
        </h1>
        <a href='https://twitter.com/nomber1910' target='_blank'>
          <FontAwesomeIcon icon={['fab','twitter']} className={styles.icon}/>
        </a>
        <a href='https://github.com/Akatsuki1910' target='_blank'>
          <FontAwesomeIcon icon={['fab','github']} className={styles.icon}/>
        </a>
      </div>
      <Background/>
    </>
  )
}

export default Home

export async function getStaticProps() {
  const text = 'aktk1910.pw'

  return {
    props: { text },
  }
}

// pages/index.vue
<template lang="pug">
.center
  h1.title aktk1910.pw
  a(href="https://twitter.com/nomber1910" target="_blank" aria-label="twitter")
    Twitter.icon
  a(href="https://github.com/Akatsuki1910" target="_blank" aria-label="github")
    Github.icon
</template>

<style lang="scss" scoped>
.center {
  text-align: center;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translateX(-50%) translateY(-50%);
  background-color: rgba($color: #000000, $alpha: 0.5);
  padding: 0 4px;
}

.title {
  color: white;
  font-family: sans-serif;
}

.icon {
  font-size: 3rem;
  transition: all 0.3s;
  margin: 5px;
  color: white;
  &:hover {
    transform: scale(1.2);
  }
}
</style>
